### ISSUE TITLE
Kits in all caps

### ISSUE THREAD

**Issue by AdriaanBoshoff** [jacobmstein/Kits#2]
When defining a kit in all caps, the kit doesn't exit even if you type the name in all caps

**Comment by jacobmstein** [comment]
See https://github.com/jacobmstein/Kits/blob/master/Kits/Kits.cs#L501. Kit names are converted to lowercase to prevent naming conflicts.

**Comment by AdriaanBoshoff** [comment]
Sorry. I only now found out that a buddy of mine manually changed the lowercase to upper in the config and that made it not list the plugin.
